module.exports = {
    API_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJpcXVhbGlmeS5jb20iLCJhdWQiOiJhcGkuaXF1YWxpZnkuY29tIiwiZXhwIjozMTcxOTU5MTUwMzMsImlhdCI6MTYyNjY1NTAzMywib3JnIjoiZ2Vvcmdlc3RyaWNrbGFuZCIsInNjb3BlIjoib3JnOmdlb3JnZXN0cmlja2xhbmQifQ.jxnH_HnRRyYEB1VL6yMv6emjQ9b4XgXXr5K1r58viVU'
  };
  